### ISSUE TITLE
No active target - cannot build

### ISSUE THREAD

**Issue by jamie85** [AtomBuild/build-xcodebuild#1]
Have installed the atom-build pack and 'build-xcodebuild' for C/C++ building.

Unable to build - I receive error message:

> No eligible build target.
> No configuration to build this project exists.

Upon "Build: select active target" (or opt+cmd+t) there are no targets to select from.

I have tried to refresh targets.

**Comment by noseglid** [comment]
`xcode-build` only runs on OS X at the moment. Can you confirm that you're using this.
If so the project root must be part of an xcode project, so `glob.sync('*.@(xcodeproj|xcworkspace)'` must be true of the project root folder.

**Comment by jamie85** [comment]
I am running on OS X.

So to confirm, I have to create the project in Xcode first, and then open the files in atom - then I will be able to build (to ensure that the xcodeproj file exists in the root folder)?  Is there a way to create this without Xcode do you know?

Sorry Im not too sure what you mean by "glob.sync" must be true.

Thanks for your help!

**Comment by noseglid** [comment]
I'm not a 100% sure about the project layout of xcode projects, but I think there must be a file named `.xcodeproj` or `.xcworkspace` in the project root folder. Maybe @kepler0 can shed some light?

**Comment by jamie85** [comment]
I just created a project in Xcode, then opened the C++ file in atom and was able to build successfully.

Its great because I can start using the amazing code completion features of atom compared to Xcode, so Im happy about that, but less so that I still have to create projects in Xcode first (although not a massive deal I guess).

Just out of interest, I want to use atom on my raspberry pi, do you know how I would go about building C/C++ in atom on linux systems from atom?

Once again thanks very much for your help!

**Comment by keplersj** [comment]
@noseglid You're spot on.

I'm gonna close this as it seems you've resolved your issue. Feel free to continue discussing or move over to Atom Slack, we're all there.
