### ISSUE TITLE
Project not detected

### ISSUE THREAD

**Issue by andrewrynhard** [AtomBuild/build-xcodebuild#4]
My project was not detected. Had to use:

```
        if (glob.sync(this.cwd + '/*.@(xcodeproj|xcworkspace)').length >= 1) {
          return true; // Project running on OS X and contains Xcode project.
        }
```

If I did:

```
glob.sync('*', this.cwd).length >= 1
```

I got a list of files/directories in `/`

**Comment by mhulse** [comment]
@andrewrynhard where did you put this code? Trying to figure this out and am having same issue.

**Comment by andrewrynhard** [comment]
@mhulse https://github.com/AtomBuild/build-xcodebuild/blob/b1fd05c1b331301ff69301625c63a5922a3dd64e/lib/main.js#L19
You will have to edit the file somewhere in `~/.atom`

**Comment by mhulse** [comment]
> @mhulse https://github.com/AtomBuild/build-xcodebuild/blob/b1fd05c1b331301ff69301625c63a5922a3dd64e/lib/main.js#L19
> You will have to edit the file somewhere in ~/.atom

Perfect! Doing now. Thanks for the quick reply! 👍

**Comment by mhulse** [comment]
Ok, that worked.

Specs:

``` bash
Version 7.3.1 (7D1014)
Swift 2
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.9.3
```

Gonna do a PR to get this code updated.

**Comment by mhulse** [comment]
Done: https://github.com/AtomBuild/build-xcodebuild/pull/6

Thanks again for your help @andrewrynhard :octocat:

**Comment by andrewrynhard** [comment]
@mhulse glad I could help.
